/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WVlAuvT0ryO
 */
import { sql } from "@vercel/postgres";
import Classified from "./Classified";
import Link from "next/link";
export const dynamic = "force-dynamic";

const classifieds = [
  {
    id: 1,
    title: "FS: Acoustic Guitar. Great condition. Perfect for beginners.",
    text: "I'm selling my acoustic guitar. It's in great condition and perfect for beginners. Comes with a case and a tuner.",
    author: {
      name: "Lee Robinson",
      username: "leerob",
      avatar: "/placeholder.svg",
    },
    createdAt: new Date("2024-03-31 12:00:00"),
    expiryDate: new Date("2024-04-30 12:00:00"),
  },
];

export async function Classifieds({
  communitySlug,
  account,
}: {
  communitySlug: string;
  account: string;
}) {
  const { rows } =
    await sql`SELECT * from classifieds where "communitySlug"=${communitySlug}`;

  return (
    <div className="mx-auto w-full max-w-5xl px-4 lg:px-6 space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">Classifieds</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Share what you are looking for or what you have to offer.
        </p>
      </div>
      <div className="space-y-6">
        <Link
          href={`/${communitySlug}/new?account=${account}`}
          className="rounded-lg border-white border-2 p-3"
        >
          New Classified
        </Link>
      </div>
      <div className="space-y-6">
        <div className="space-y-6">
          {rows.map((classified) => (
            <Classified key={classified.id} data={classified} />
          ))}
        </div>
        <div className="border-t border-gray-200 dark:border-gray-800" />
      </div>
    </div>
  );
}

function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  );
}
